project_id = "elydnykhwsvrtjonkvxj"

[functions.musicbrainz]
verify_jwt = false

[functions.check-new-releases]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false

[functions.prewarm-artist-images]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.broadcast-app-update]
verify_jwt = false

[functions.email-health-check]
verify_jwt = false
