project_id = "elydnykhwsvrtjonkvxj"

[functions.musicbrainz]
verify_jwt = false

[functions.check-new-releases]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false
